### ISSUE TITLE
Design dapp for browsing kernel standard library releases and vouching

### ISSUE THREAD

**Issue by spalladino** [OpenZeppelin/openzeppelin-labs#78]
Design a user interface for browsing available kernel versions, and managing own ZepTokens (viewing availability, staking, unstaking, transferring stake, etc). Consider adding metadata to kernel instances on-chain if needed.

**Comment by spalladino** [comment]
@maraoz let's discuss whether we want to include this for the MVP

**Comment by Abeanna** [comment]
> Design a user interface for browsing available kernel versions, and managing own ZepTokens (viewing availability, staking, unstaking, transferring stake, etc). Consider adding metadata to kernel instances on-chain if needed.

Ok
